config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  delete "destroy_user_session", to: "devise/sessions#destroy"
  devise_scope :user do
    get "addresses", to: "users/registrations#new_address"
    post "addresses", to: "users/registrations#create_address"
    get "user_show", to: "users/registrations#show"
    get "user_destroy", to: "users/sessions#index"
  end
  root 'items#index'

  resources :items do 
    resources :images, only: [:new, :create]
    collection do
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'purchase'
      get 'pay'
    end
  end
    
  resources :creditcards, only: [:new, :create, :show, :destroy] do
    collection do
      get 'done_create'
      get 'done_destroy'
    end
  end

  post "items/:id/pay", to: 'items#pay'
  
end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
  belongs_to :user

  validates :customer_id, presence: true 
  validates :card_id    , presence: true

end

app/controllers/creditcards_controller.rb
class CreditcardsController < ApplicationController
  before_action :set_secret_key, except:[:new]
  before_action :set_user_card, only:[:show, :destroy]
  before_action :set_customer, only:[:show, :destroy]
  
  require "payjp"

  def new
    @card = Creditcard.new
    card = Creditcard.where(user_id: current_user.id)
    if card.exists?
      redirect_to creditcard_path(current_user.id)
      flash[:notice] = "カード情報は既に登録されています"
    end
  end

  def create
    if params[:creditcard][:number].blank? || params[:creditcard][:cvc].blank?
      redirect_to action: "new"
      flash[:alert] = "全ての項目を正しく入力して下さい"
    else
      token = Payjp::Token.create({
        card: {
          number:     params[:creditcard][:number],
          cvc:        params[:creditcard][:cvc],
          exp_month:  params[:creditcard][:exp_month],
          exp_year:   params[:creditcard][:exp_year]
          }},
          {'X-Payjp-Direct-Token-Generate': 'true'} 
        )
      if token.blank?
        redirect_to new_card_path
        flash[alert] = "カード情報が無効です"
      else
        customer = Payjp::Customer.create(card: token)
        card = Creditcard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
        card.save!
        if card.save!
          redirect_to done_create_creditcards_path
        else
          redirect_to new_card_path
          flash[:alert] = "カード情報登録に失敗しました"
        end
      end
    end
  end

  def show
    if @card.blank?
      redirect_to action: "new"
      flash[:notice] = "カード情報が未登録です"
    else
      @default_card_information = @customer.cards.data[0]
    end
  end

  def destroy
    @customer.delete
    @card.delete
    if @card.destroy
      # redirect_to user_show_path(current_user.id)
      redirect_to done_destroy_creditcards_path
    else
      redirect_to creditcard_path(current_user.id)
      flash[:alert] = "カード情報削除に失敗しました"
    end
  end

  private

  def set_secret_key
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
  end

  def set_user_card
    @card = Creditcard.find_by(user_id: current_user.id)
  end

  def set_customer
    @customer = Payjp::Customer.retrieve(@card.customer_id)
  end

end

app/views/creditcards/create.html.haml
完了

app/views/creditcards/done_create.html.haml
.completion__notice
  = link_to "#" do
    = image_tag "/material/logo/logo.png", class: "completion__notice--logo", alt: "FURIMA"
  .completion__notice--main カードの登録が完了しました
  = link_to "トップへ戻る", root_path, class: "completion__notice--link"

app/views/creditcards/done_destroy.html.haml
.completion__notice
  = link_to "#" do
    = image_tag "/material/logo/logo.png", class: "completion__notice--logo", alt: "FURIMA"
  .completion__notice--main 削除が完了しました
  = link_to "トップへ戻る", root_path, class: "completion__notice--link"

app/views/creditcards/new.html.haml
= render 'layouts/notifications'
.credit-card
  .credit-card_title
    %h2 クレジットカード情報入力
  .credit-card_box
    .credit-card_box_inner
      = form_with model: @card, url: creditcards_path, local: true do |f|
        .credit-card_box_inner_number
          = f.label :カード番号, class: 'label'
          %span.red 必須
          %br
          = f.text_field :number, type: 'text', class: 'input-number', placeholder: '半角数字のみ', maxlength: "16"
        .credit-card_box_inner_deadline
          = f.label :有効期限, class: 'label'
          %span.red 必須
          .credit-card_box_inner_deadline_data
            = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'input-expire'
            %p 月
            = f.select :exp_year, [["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'input-expire'
            %p 年
        .credit-card_box_inner_number
          = f.label :セキュリティコード, class: 'label'
          %span.red 必須
          = f.text_field :cvc, type: 'text', class: 'input-number', placeholder: 'カード背面4桁もしくは3桁の番号', maxlength: "4"
        .credit-card_box_inner_bottom#card_token
          = f.submit '追加する', id: 'token_submit'

app/views/creditcards/show.html.haml
= render 'layouts/notifications'
.credit-card
  .credit-card_title
    クレジットカード情報
  .credit-card_info
    .credit-card_info_number
      カード番号
      %br
      %p= "**** **** **** " + @default_card_information.last4
    .credit-card_info_term
      カード有効期限
      %br
      - exp_month = @default_card_information.exp_month.to_s
      - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
      %p= exp_month + " / " + exp_year
    .credit-card_info_btn
      = form_tag(creditcard_path(current_user.id), method: :delete, id: 'charge-form',  name: "inputForm", data: {confirm: "カード情報を削除しますか？"}) do
        %input{ type: "hidden", name: "card_id", value: "" }
        %button.delete-btn 削除する
    .credit-card_info_text
      ＊編集される場合は一度削除してから再登録をお願いします。