config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  delete "destroy_user_session", to: "devise/sessions#destroy"
  devise_scope :user do
    get "addresses", to: "users/registrations#new_address"
    post "addresses", to: "users/registrations#create_address"
    get "user_show", to: "users/registrations#show"
    get "user_destroy", to: "users/sessions#index"
  end
  root 'items#index'

  resources :items do 
    resources :images, only: [:new, :create]
    collection do
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'purchase'
      get 'pay'
    end
  end
    
  resources :creditcards, only: [:new, :create, :show, :destroy] do
    collection do
      get 'done_create'
      get 'done_destroy'
    end
  end

  post "items/:id/pay", to: 'items#pay'
  
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :delivery_charge
  belongs_to_active_hash :delivery_dates
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :condition

  belongs_to :category
  belongs_to :user
  has_one :order
  has_many :images
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :name, presence: true, length: {maximum: 40}
  validates :description, presence: true, length: {maximum: 1000}
  validates :condition_id, presence: true
  validates :delivery_charge_id, presence: true
  validates :prefecture_id, presence: true
  validates :delivery_dates_id, presence: true
  validates :price, presence: true, numericality: {greater_than: 300, less_than: 9999999}
  validates :status, presence: true
  validates_associated :images
  validates :images, presence: true

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only:[:show, :destroy, :edit, :update, :purchase, :pay]
  before_action :move_to_index, except: [:index, :show, :search]
  before_action :move_to_index_unless_owner, only: [:edit, :update, :destroy]
  before_action :set_card_and_key, only: [:purchase, :pay]

  require "payjp"
  
  def index
    @items = Item.includes(:images).where(status: 1).order('id DESC').limit(3)
  end

  def new
    @item = Item.new
    @item.images.new
    @category_parent_array = Category.where(ancestry: nil)
  end
  


  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @images = @item.images
    @top_image = @images.first
    @parents = Category.all
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item.id)
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render :edit
    end
  end

  def purchase
    if user_can_purchase_item?
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.data[0]
    else
      redirect_to root_path
      flash[:alert] = "購入処理が失敗しました"
    end
  end

  def pay
    if user_can_purchase_item?
      @item.status = 2 # 購入済に変更
      @item.save!
      @charge = Payjp::Charge.create(
        amount: @item.price,
        customer: @card.customer_id,
        currency: "jpy"
      )
    else
      redirect_to item_path(@item)
      flash[:alert] = "支払い処理が失敗しました"
    end
  end

  def get_category_children
    @category_children = Category.find(params[:parent_id]).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  def search
    @q = Item.ransack(params[:q])
    @items = @q.result.includes(:images).to_a.uniq
    @parents = Category.all
    @categories = Category.all
    if @q_header
      params[:q] = {sorts: "created_at DESC"}
      @items = @q_header.result.includes(:images).to_a.uniq
    end
  end
  
  private

  def item_params
    params.require(:item).permit(:name, :description, :category_id, :delivery_charge_id, :prefecture_id, :delivery_dates_id, :price, :status, :condition_id, images_attributes: [:image, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def move_to_index_unless_owner
    redirect_to action: :index unless user_signed_in? && current_user.id == @item.user_id
  end

  def set_card_and_key
    @card = Creditcard.find_by(user_id: current_user.id)
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
  end

  def user_can_purchase_item?
    @card.present? && @item.status === 1 # status[1] = 購入可能
  end
  
end

app/views/items/_erroritems.html.haml
- if item.errors.any?
  .error_explanation
    %ul.error_explanation__list
      - item.errors.full_messages.each do |message|
        %li 
          = icon('fas', 'exclamation-triangle')
          = message

app/views/items/_form.html.haml
= form_with model: item, class: "mainContainer__form", local: true do |f|
  = render partial: "erroritems", locals: { item: item }
  .image-box
    .image-box__name
      出品画像
      .image-box__name-require
        必須
    .image-box__comment
      最大10枚までアップロードできます
    .image-box__fields
      #image-box
        - if item.persisted?
          = f.fields_for :images, :item do |i|
            .js-file_group{data: {index: i.index.to_s}}
              .preview-none
                .js-image-zone
                  - if item.persisted?
                    = image_tag item.images[i.index].image.url, data: { index: i.index }, width: "138px", height: "82px"
                .js-edit 変更
                .js-remove 削除
              %label.input
                .input__box
                  .input__box__cam-icon
                    %i.fa.fa-camera.fa-lg
                  %p.input__box__p
                    ここをクリックしてアップロード
                = i.file_field :image, class: 'js-file', style: 'display:none'
            - if item.persisted?
              = i.check_box :_destroy, data:{ index: i.index }, class: "hidden-destroy"
        - else
          = f.fields_for :images, item do |i|
            .js-file_group{data: {index: i.index.to_s}}
              .preview-none
                .js-image-zone
                  - if item.persisted?
                    = image_tag item.images[i.index].image.url, data: { index: i.index }, width: "138px", height: "82px"
                .js-edit 変更
                .js-remove 削除
              %label.input
                .input__box
                  .input__box__cam-icon
                    %i.fa.fa-camera.fa-lg
                  %p.input__box__p
                    ここをクリックしてアップロード
                = i.file_field :image, class: 'js-file', style: 'display:none'
        - if item.persisted?
          .js-file_group{data: {index: item.images.count}}
            .preview-none
              .js-image-zone
              .js-edit 変更
              .js-remove 削除
            %label.input
              = file_field_tag :image, name: "item[images_attributes][#{item.images.count}][image]", class: 'js-file', style: "display:none"
              .input__box
                .input__box__cam-icon
                  %i.fa.fa-camera.fa-lg
                %p.input__box__p
                  ここをクリックしてアップロード
      #how-many-image

  .item-form-box
    .item-form-box__upper
      .item-form-box__upper__name
        商品名
        .item-form-box__upper__name__require
          必須
      .item-form__title
        =f.text_field :name, placeholder: "40文字まで" 
      .errorbox-fortext
        %p.errorbox-fortext__errormessage
          入力してください
    .item-form-box__under
      .item-form-box__under__name
        商品の説明
        .item-form-box__under__name__require
          必須
      .item-form-box__under__textarea
        =f.text_area :description, placeholder: '商品の説明（必須1,000文字以内)&#13;&#10;（色、素材、重さ、定価、注意点など）&#13;&#10; &#13;&#10;例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。'.html_safe
      .errorbox-fortextarea
        %p.errorbox-fortextarea__errormessage
          入力してください

  .selectbox-block
    %p.selectbox-block__description
      商品の詳細
    .selectwrapper
      .selectwrapper__name
        カテゴリー
        .selectwrapper__name__require
          必須
      .selectbox-category
        - if item.persisted? || item.category.present?
          = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {prompt: "選択してください", selected: Category.find(item.category_id).parent.parent.id.to_s}, {id: 'parent_category'}
          #children_wrapper.selectbox-category__added
            .selectbox1
              = select_tag :category_id, options_for_select(Category.find(Category.find(item.category_id).parent.parent.id).children.map{|i|[i.name, i.id, { 'data-category' => i.id }]}, selected: Category.find(item.category_id).parent.id.to_s), id: "child_category", class: "selectbox-category--select", name: "item[category_id]"
          #grandchildren_wrapper.selectbox-category__added
            .selectbox2
              = select_tag :category_id, options_for_select(Category.find(Category.find(item.category_id).parent.id).children.map{|i|[i.name, i.id, { 'data-category' => i.id }]}, selected: item.category_id.to_s), id: "grandchild_category", class: "selectbox-category--select", name: "item[category_id]"
        - else
          = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {prompt: '選択してください'}, {id: 'parent_category'}
    .selectwrapper
      .selectwrapper__name
        商品の状態
        .selectwrapper__name__require
          必須
      .selectbox
        = f.collection_select :condition_id, Condition.all, :id, :condition ,{prompt: "選択してください"}, class: "select-class-for-error"
      .errorbox
        %p.errorbox__errormessage
          選択されていません
  .selectbox-block
    %p.selectbox-block__description
      配送について
    .selectwrapper
      .selectwrapper__name
        配送料の負担
        .selectwrapper__name__require
          必須
      .selectbox
        = f.collection_select :delivery_charge_id, DeliveryCharge.all, :id, :name ,{prompt: "選択してください"}, class: "select-class-for-error"
      .errorbox
        %p.errorbox__errormessage
          選択されていません
    .selectwrapper
      .selectwrapper__name
        発送元の地域
        .selectwrapper__name__require
          必須
      .selectbox
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name ,{prompt: "選択してください"}, class: "select-class-for-error"
      .errorbox
        %p.errorbox__errormessage
          選択されていません
    .selectwrapper
      .selectwrapper__name
        発送までの日数
        .selectwrapper__name__require
          必須
      .selectbox
        = f.collection_select :delivery_dates_id, DeliveryDates.all, :id, :name, {prompt: "選択してください"}, class: "select-class-for-error"
      .errorbox
        %p.errorbox__errormessage
          選択されていません

  .selectbox-block-money
    .selectbox-block-money__box
      %p.selectbox-block-money__box__upper
        価格（¥300〜9,999,999）
      .selectbox-block-money__box__middle
        .selectbox-block-money__box__middle__left
          販売価格
          .selectbox-block-money__box__middle__left__required
            必須
        .selectbox-block-money__box__middle__right
          ¥
          = f.number_field :price, class: "price_calc", type: "number"
          .errorbox-forprice
            %p.errorbox-forprice__errormessage
              ¥300〜9,999,999に設定してください
      .selectbox-block-money__box__bellow
        %p.selectbox-block-money__box__bellow__left
          販売手数料（3%）
        %p.selectbox-block-money__box__bellow__right
          %input{type: "number", style: "display: none"}
    .selectbox-block-money__profit
      %p.selectbox-block-money__profit__left
        販売利益
      %p.selectbox-block-money__profit__right
        %input{type: "number", style: "display: none"}

  .item-submit
    %label
      = f.submit style: "display:none"
      %p.item-submit__submit-btn
        出品する
    = link_to root_path class: "link-item-submit" do
      .item-submit__back-btn
        もどる
  %p.item-submit-attention
    禁止されている
    %a.link-item-submit 行為
    および
    %a.link-item-submit 出品物
    を必ずご確認ください。
    %a.link-item-submit 偽ブランド品
    や
    %a.link-item-submit 盗品物
    などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして
    %a.link-item-submit 加盟店規約
    に同意したことになります。

  .regulation-footer
    %ul.regulation-footer__list
      %li
        =link_to '#', class: "regulation-footer__list__link" do
          プライバシーポリシー
      %li
        =link_to '#', class: "regulation-footer__list__link" do
          フリマ利用規約
      %li
        =link_to '#', class: "regulation-footer__list__link" do
          特定商取引に関する表記
    .regulation-footer__logo
      .regulation-footer__logo__box
        = link_to root_path do
          = image_tag "/material/logo/logo-white.png", size: "185x53"
        %p.regulation-footer__logo__box__company
          © FURIMA, Inc.

app/views/items/_main_header.html.haml
.main_header
  .main_header_inner
    .main_header_inner_box
      .main_header_inner_box_left
        =link_to root_path do
          =image_tag "/material/logo/logo.png"
      .main_header_inner_box_right
        = search_form_for(@q_header, url: search_items_path) do |f|
          = f.search_field :name_cont, id: "header-form", placeholder: "キーワードから探す"
          = button_tag type: "submit" do
            = image_tag '/material/icon/icon-search 1.png'
      .main_header_inner_box_list
    .main_header_inner_low
      .main_header_inner_low_leftLists
        .main_header_inner_low_leftLists_left
          =link_to '#' do
            カテゴリー
        .main_header_inner_low_leftLists_right
          =link_to '#' do
            ブランド
      .main_header_inner_low_rightLists
        - if user_signed_in?
          .main_header_inner_low_rightLists_left
            = link_to "マイページ", user_show_path(current_user)
          .main_header_inner_low_rightLists_right
            = link_to "ログアウト", destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"}
        - else
          .main_header_inner_low_rightLists_left
            = link_to "ログイン", new_user_session_path
          .main_header_inner_low_rightLists_right
            = link_to "新規会員登録", new_user_registration_path

app/views/items/index.html.haml
= render 'layouts/notifications'
.main
  = render "items/main_header"
  .main_page
    .main_page_visual
      .main_page_visual_content
        .main_page_visual_content_title
          人生を変えるフリマアプリ
        .main_page_visual_content_text
          .p FURIMAはだれでもかんたんに出品・購入できる
          .p フリマアプリです
        .main_page_visual_content_btn
          .main_page_visual_content_btn_a
            =link_to '#' do
              -# =image_tag '/material/icon/app-store'
          .main_page_visual_content_btn_b
            =link_to '#' do
              -# =image_tag '/google-play'
    .main_page_reason
      .main_page_reason_title
        FURIMAが選ばれる3つの理由

      .main_page_reason_lists
        .main_page_reason_lists_list
          .main_page_reason_lists_list_picture
            .span 1
            =image_tag '/material/pict/pict-reason-01.jpg'
          .main_page_reason_lists_list_subtitle
            %span 3分
            ですぐに出品
          .main_page_reason_lists_list_text
            スマホで入力するだけで簡単に出品できる！
        .main_page_reason_lists_list
          .main_page_reason_lists_list_picture
            .span 2
            =image_tag '/material/pict/pict-reason-02.jpg'
          .main_page_reason_lists_list_subtitle
            %span シンプル
            で使いやすい
          .main_page_reason_lists_list_text
            めんどくさい入力は必要なく、検索も購入もスムーズ！
        .main_page_reason_lists_lastList
          .main_page_reason_lists_lastList_picture
            .span 3
            =image_tag '/material/pict/pict-reason-03.jpg'
          .main_page_reason_lists_lastList_subtitle
            手数料
            %span 業界最安
          .main_page_reason_lists_lastList_text
            最大3%でお得に出品&購入！
    .main_page_download
      .main_page_download_inner
        .main_page_download_inner_title
          会員数日本一位
        .main_page_download_inner_text
          .br FURIMAは、フリマアプリで最も人気。
          .br 出品・購入回数も業界最多です！
          .br ほしかったあの商品に出会えるかもしれません。
        .main_page_download_inner_btn
          .main_page_download_inner_btn_a
            =link_to '#' do
              -# =image_tag '/assets/apple-store'
          .main_page_download_inner_btn_b
            =link_to '#' do
              -# =image_tag '/assets/google-pray'
    .main_page_chara
      .main_page_chara_head
        FURIMAの特徴
      .main_page_chara_lists
        .main_page_chara_lists_list
          .main_page_chara_lists_list_picture
            = image_tag "/material/icon/icon-01.png"
          .main_page_chara_lists_list_subtitle
            簡単に売り買いできる
          .main_page_chara_lists_list_text
            スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        .main_page_chara_lists_list
          .main_page_chara_lists_list_picture
            = image_tag "/material/icon/icon-03.png"
          .main_page_chara_lists_list_subtitle
            売上金は即日振込みに対応
          .main_page_chara_lists_list_text
            午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
        .main_page_chara_lists_list
          .main_page_chara_lists_list_picture
            = image_tag "/material/icon/icon-04.png"
          .main_page_chara_lists_list_subtitle
            様々な支払いに対応
          .main_page_chara_lists_list_text
            お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
    .main_page_pickup
      .main_page_pickup_head
        ピックアップカテゴリー
      .main_page_pickup_box
        .main_page_pickup_box_title
          =link_to '#' do
            新規投稿商品
        .main_page_pickup_box_lists
          - @items.each do |item|
            .main_page_pickup_box_lists_list
              =link_to item_path(item.id) do
                .main_page_pickup_box_lists_list_picture
                  = image_tag "#{item.images[0].image_url}", class:".main_page_pickup_box_lists_list_picture__box"
                .main_page_pickup_box_lists_list_text
                  .main_page_pickup_box_lists_list_text_name
                    = item.name
                  .main_page_pickup_box_lists_list_text_data
                    %ul 
                      %li= item.price
                      %li
                        %i.fa.fa-star
                          0
                    .p
                      (税込)
    .main_page_pickup
      .main_page_pickup_head
        ピックアップブランド
      .main_page_pickup_box
        .main_page_pickup_box_title
          =link_to '#' do
            アーカイバ
        .main_page_pickup_box_lists
          .main_page_pickup_box_lists_list
            =link_to '#' do
              .main_page_pickup_box_lists_list_picture
                =image_tag "/material/pict/pict-reason-01.jpg"
              .main_page_pickup_box_lists_list_text
                .main_page_pickup_box_lists_list_text_name
                  prodact3
                .main_page_pickup_box_lists_list_text_data
                  %ul
                    %li 30000円
                    %li
                      %i.fa.fa-star
                        0
                  .p
                    (税込)
          .main_page_pickup_box_lists_list
            =link_to '#' do
              .main_page_pickup_box_lists_list_picture
                = image_tag "/material/pict/pict-reason-02.jpg"
              .main_page_pickup_box_lists_list_text
                .main_page_pickup_box_lists_list_text_name
                  prodact2
                .main_page_pickup_box_lists_list_text_data
                  %ul
                    %li 20000円
                    %li
                      %i.fa.fa-star
                        0
                  .p
                    (税込)
          .main_page_pickup_box_lists_list
            =link_to '#' do
              .main_page_pickup_box_lists_list_picture
                = image_tag "/material/pict/pict-reason-03.jpg"
              .main_page_pickup_box_lists_list_text
                .main_page_pickup_box_lists_list_text_name
                  prodact1
                .main_page_pickup_box_lists_list_text_data
                  %ul
                    %li 10000円
                    %li
                      %i.fa.fa-star
                        0
                  .p
                    (税込)
  = render "items/main_footer"
  - if user_signed_in?
    =link_to new_item_path do
      .main_btn
        .main_btn_text
          出品する
          =image_tag '/material/icon/icon_camera.png'

app/views/items/purchase.html.haml
%main
  .purchase-container
    .purchase-container__allbox
      .purchase-container__allbox__header
        = link_to (image_tag "/material/logo/logo.png", width: "185", height: "53"), root_path

      .purchase-mainbox
        .purchase-mainbox__top
          .purchase-mainbox__top__text
            購入内容の確認
          %hr

        .purchase-mainbox__item
          .purchase-mainbox__item__box
            .purchase-mainbox__item__box__img
              = image_tag @item.images[0].image.url, size: "90x90"
            .purchase-mainbox__item__box__text
              %p.title
                = @item.name
              %p.price
                = "¥ #{@item.price} (税込）"

        .purchase-mainbox__detail
          .purchase-mainbox__detail__box
            .purchase-mainbox__detail__box__price
              %p.price-text
                支払い金額
              %p.buy-price
                = "¥  #{@item.price}"
            .purchase-mainbox__detail__box__payment
              .purchase-mainbox__detail__box__payment__type
                %p.title
                  支払い方法
                .purchase-mainbox__detail__box__payment__type__card-info
                  - if @default_card_information.blank?
                    =link_to "クレジットカードを登録する",new_creditcard_path
                  - else
                    .card_number
                      クレジットカード
                      %br/
                      = "**** **** **** " + @default_card_information.last4
                      .card_number__change
                        =link_to "変更する",new_creditcard_path
                    .card_expire
                      有効期限
                      %br/
                      - exp_month = @default_card_information.exp_month.to_s
                      - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                      = exp_month + " / " + exp_year
                    .card_icon
                      %br/
                      - if @default_card_information.brand == "Visa"
                        = image_tag "credit_card_logo/Visa.png", class: "visa card"
                      - elsif @default_card_information.brand == "MasterCard"
                        = image_tag "credit_card_logo/MasterCard.png", class: "mastercard card"
                      - elsif @default_card_information.brand == "JCB"
                        = image_tag "credit_card_logo/JCB.png", class: "jcb card"
                      - elsif @default_card_information.brand == "American Express"
                        = image_tag "credit_card_logo/American_Express.png", class:"american-express card"
                      - elsif @default_card_information.brand == "Diners Club"
                        = image_tag "credit_card_logo/diners-club.png", class: "diners-club card"

            .purchase-mainbox__detail__box_payment__type__place
              .purchase-mainbox__detail__place__address
                %p.title
                  配達先
                %p.detail
                  ="〒#{current_user.address.postcode}"
                  %br/
                  =current_user.address.prefecture
                  =current_user.address.city
                  =current_user.address.block                

            .purchase-mainbox__detail__box_payment__type__notice
              郵便局/コンビニ受取をご希望の方は、購入後に取引画面から受取場所を変更をすることが可能です。出品者が発送作業を開始した後は受取場所の変更ができませんので、早めに変更を行ってください。
            .purchase-mainbox__detail__box_payment__type__submit-btn
              = link_to pay_item_path, method: :POST do
                %button{ onclick: "location.href='./pay.html.haml'", type:  "“button”",class:"submit-btn"}購入する

        .regulation-footer
          %ul.regulation-footer__list
            %li
              =link_to '#', class: "regulation-footer__list__link" do
                プライバシーポリシー
            %li
              =link_to '#', class: "regulation-footer__list__link" do
                フリマ利用規約
            %li
              =link_to '#', class: "regulation-footer__list__link" do
                特定商取引に関する表記
          .regulation-footer__logo
            .regulation-footer__logo__box
              = link_to root_path do
                = image_tag "/material/logo/logo-white.png", size: "185x53"
              %p.regulation-footer__logo__box__company
                © FURIMA, Inc.

app/views/items/show.html.haml
= render 'items/main_header'

.category-bar
  FURIMA
  = icon('fas', 'chevron-right')
  ベビー・キッズ
  = icon('fas', 'chevron-right')
  ベビー服(男女兼用) ~95cm
  = icon('fas', 'chevron-right')
  アウター
  = icon('fas', 'chevron-right')
  商品名

.item
  .item__item-box
    %h1.item__item-box__name
      = @item.name
    -# 大イメージ
    .item__item-box__image0
      = image_tag @top_image.image.url, size: "560x346"
    -# 小イメージ
    %ul#image_list.item__item-box__images
      - @images.each do |image|
        %li.item__item-box__images__image
          = image_tag image.image.url, size: "140x87"
    
    %p.item__item-box__price
      = "¥#{@item.price}"
    %p.item__item-box__price-description
      %span 
        = @item.delivery_charge.name

    %p.item__item-box__description
      = @item.description

    %table.item__item-box__details
      %tr
        %th
          出品者
        %td
          = @item.user.nickname
      %tr
        %th
          カテゴリー
        %td
          - @parents.each do |parent|
            - if @item.category_id == parent.id
              %p
                = link_to '#' do
                  = parent.parent.parent.name
              %p
                = link_to '#' do
                  = parent.parent.name
              %p
                = link_to '#' do
                  = parent.parent.parent.name
      %tr
        %th
          ブランド
        %td
          - if @item.brand.present?
            = @item.brand
      %tr
        %th
          商品のサイズ
        %td
          - if @item.brand.present?
            = @item.brand
      %tr
        %th
          商品の状態
        %td
          = @item.condition.condition
      %tr
        %th
          配送料の負担
        %td
          = @item.delivery_charge.name
      %tr
        %th
          発送元の地域
        %td
          = link_to '#' do
            = @item.prefecture.name
      %tr
        %th
          発送日の目安
        %td
          = @item.delivery_dates.name

    .item__item-box__btn-box
      .item__item-box__btn-box__favorite-btn
        = icon('fas', 'star')
        %span お気に入り 
        %span 0
      = link_to '#' do
        .item__item-box__btn-box__report-btn
          = icon('fas', 'flag')
          不適切な商品の通報
    - if user_signed_in? && current_user.id != @item.user.id && @item.status == 1 #  status[1] = 購入可能
      .item__item-box__submit
        = link_to "購入画面へ進む", purchase_item_path(@item), class: "item__item-box__submit-btn" 
    - if user_signed_in? && current_user.id != @item.user.id && @item.status == 2 #  status[2] = 購入済
      .item__item-box__submit
        %span.item__item-box__soldout
          売り切れ
    - if user_signed_in? && current_user.id == @item.user.id && @item.status == 2 #  status[2] = 購入済
      .item__item-box__submit
        %span.item__item-box__soldout
          販売済
    - if user_signed_in? && current_user.id == @item.user.id
      .item__item-box__show
        .item__item-box__show-edit
          = link_to "編集", edit_item_path(params[:id]), class: "item__item-box__show-edit"
        .item__item-box__show-delete
          = link_to "削除", item_path(@item), method: :delete, class: "item__item-box__show-delete"

  .item__comment-box
    %textarea.item__comment-box__textarea
    .item__comment-box__attention
      %span 相手のことを考え丁寧なコメントを心がけましょう。
      %span 不快な言葉遣いなどは利用制限や退会処分となることがあります。
    .item__comment-box__comment-submit-btn
      = icon('fas', 'comment')
      コメントする

  .item__other-items-box
    .item__other-items-box__prev-next
      .item__other-items-box__prev-next__prev
        = link_to '#' do
          %span
            = icon('fas', 'chevron-left')
          前の商品
      .item__other-items-box__prev-next__next
        = link_to '#' do
          次の商品
          %span
            = icon('fas', 'chevron-right')
    .item__other-items-box__more-items
      = link_to '#' do
        このカテゴリーをもっと見る

= render 'items/main_footer'

-# 小イメージが５枚以上の時、ulに'overflown'クラスをつけてスタイルを変更
:javascript
  (()=>{
    const images = document.getElementsByClassName('item__item-box__images__image');
    const images_array = Array.from(images);
    if (images_array.length > 4) {
      document.getElementById('image_list').classList.add('overflown');
    }
  })();